evennements_index:
    path:     /
    defaults: { _controller: "eventBundle:evennements:index" }
    methods:  GET

evennements_show:
    path:     /{id}/show
    defaults: { _controller: "eventBundle:evennements:show" }
    methods:  GET

evennements_new:
    path:     /new
    defaults: { _controller: "eventBundle:evennements:new" }
    methods:  [GET, POST]

evennements_edit:
    path:     /{id}/edit
    defaults: { _controller: "eventBundle:evennements:edit" }
    methods:  [GET, POST]

evennements_delete:
    path:     /{id}/delete
    defaults: { _controller: "eventBundle:evennements:delete" }
    methods:  DELETE
evenements_showgeo:
    path: /showgeo/{x}/{y}
    defaults: { _controller: "eventBundle:evennements:geo" }
    methods:  [GET, POST]
